type ShareBadgeInput = {
  percentage: number
  performanceLabel: string
  scoreLabel: string
  detailLabel: string
  dateLabel: string
}

function escapeXml(value: string) {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;')
}

export function buildShareBadgeSvg({
  percentage,
  performanceLabel,
  scoreLabel,
  detailLabel,
  dateLabel,
}: ShareBadgeInput): string {
  const scoreColor = percentage >= 80 ? '#16a34a' : percentage >= 60 ? '#d97706' : '#dc2626'

  return `<?xml version="1.0" encoding="UTF-8"?>
<svg width="1200" height="628" viewBox="0 0 1200 628" fill="none" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="1200" y2="628" gradientUnits="userSpaceOnUse">
      <stop stop-color="#0f2744"/>
      <stop offset="0.55" stop-color="#144d6a"/>
      <stop offset="1" stop-color="#1f6f6d"/>
    </linearGradient>
  </defs>
  <rect width="1200" height="628" rx="36" fill="url(#bg)"/>
  <circle cx="1080" cy="90" r="160" fill="#5dd6cf" fill-opacity="0.18"/>
  <circle cx="110" cy="560" r="190" fill="#8fb8ff" fill-opacity="0.14"/>
  <rect x="56" y="52" width="1088" height="524" rx="28" fill="white" fill-opacity="0.10" stroke="rgba(255,255,255,0.22)"/>
  <text x="90" y="120" fill="#C8E8FF" font-family="Arial, sans-serif" font-size="24" font-weight="700" letter-spacing="4">EXCEL SKILLS BADGE</text>
  <text x="90" y="190" fill="white" font-family="Arial, sans-serif" font-size="56" font-weight="700">Excel Mastery Quiz</text>
  <text x="90" y="240" fill="#D6EBFF" font-family="Arial, sans-serif" font-size="30">Shareable performance snapshot</text>
  <rect x="90" y="292" width="240" height="184" rx="28" fill="white"/>
  <text x="122" y="358" fill="${scoreColor}" font-family="Arial, sans-serif" font-size="88" font-weight="700">${percentage}%</text>
  <text x="122" y="404" fill="#183251" font-family="Arial, sans-serif" font-size="28" font-weight="700">${escapeXml(
    performanceLabel
  )}</text>
  <text x="122" y="442" fill="#5A6F8A" font-family="Arial, sans-serif" font-size="24">${escapeXml(scoreLabel)}</text>
  <text x="390" y="340" fill="white" font-family="Arial, sans-serif" font-size="34" font-weight="700">${escapeXml(
    detailLabel
  )}</text>
  <text x="390" y="392" fill="#D6EBFF" font-family="Arial, sans-serif" font-size="26">Completed ${escapeXml(
    dateLabel
  )}</text>
  <text x="390" y="454" fill="#D6EBFF" font-family="Arial, sans-serif" font-size="24">Generated by Excel Mastery Quiz</text>
</svg>`
}
